// source: service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_pb = require('./model_pb.js');
goog.object.extend(proto, model_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.order.QueryByIdResult', null, global);
goog.exportSymbol('proto.order.ToOrderResult', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.order.QueryByIdResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.order.QueryByIdResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.order.QueryByIdResult.displayName = 'proto.order.QueryByIdResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.order.ToOrderResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.order.ToOrderResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.order.ToOrderResult.displayName = 'proto.order.ToOrderResult';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.order.QueryByIdResult.prototype.toObject = function(opt_includeInstance) {
  return proto.order.QueryByIdResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.order.QueryByIdResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.order.QueryByIdResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    handleresult: (f = msg.getHandleresult()) && common_pb.HandleResult.toObject(includeInstance, f),
    order: (f = msg.getOrder()) && model_pb.Order.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.order.QueryByIdResult}
 */
proto.order.QueryByIdResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.order.QueryByIdResult;
  return proto.order.QueryByIdResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.order.QueryByIdResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.order.QueryByIdResult}
 */
proto.order.QueryByIdResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.HandleResult;
      reader.readMessage(value,common_pb.HandleResult.deserializeBinaryFromReader);
      msg.setHandleresult(value);
      break;
    case 2:
      var value = new model_pb.Order;
      reader.readMessage(value,model_pb.Order.deserializeBinaryFromReader);
      msg.setOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.order.QueryByIdResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.order.QueryByIdResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.order.QueryByIdResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.order.QueryByIdResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHandleresult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.HandleResult.serializeBinaryToWriter
    );
  }
  f = message.getOrder();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      model_pb.Order.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.HandleResult handleResult = 1;
 * @return {?proto.common.HandleResult}
 */
proto.order.QueryByIdResult.prototype.getHandleresult = function() {
  return /** @type{?proto.common.HandleResult} */ (
    jspb.Message.getWrapperField(this, common_pb.HandleResult, 1));
};


/**
 * @param {?proto.common.HandleResult|undefined} value
 * @return {!proto.order.QueryByIdResult} returns this
*/
proto.order.QueryByIdResult.prototype.setHandleresult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.order.QueryByIdResult} returns this
 */
proto.order.QueryByIdResult.prototype.clearHandleresult = function() {
  return this.setHandleresult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.order.QueryByIdResult.prototype.hasHandleresult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Order order = 2;
 * @return {?proto.order.Order}
 */
proto.order.QueryByIdResult.prototype.getOrder = function() {
  return /** @type{?proto.order.Order} */ (
    jspb.Message.getWrapperField(this, model_pb.Order, 2));
};


/**
 * @param {?proto.order.Order|undefined} value
 * @return {!proto.order.QueryByIdResult} returns this
*/
proto.order.QueryByIdResult.prototype.setOrder = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.order.QueryByIdResult} returns this
 */
proto.order.QueryByIdResult.prototype.clearOrder = function() {
  return this.setOrder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.order.QueryByIdResult.prototype.hasOrder = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.order.ToOrderResult.prototype.toObject = function(opt_includeInstance) {
  return proto.order.ToOrderResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.order.ToOrderResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.order.ToOrderResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    handleresult: (f = msg.getHandleresult()) && common_pb.HandleResult.toObject(includeInstance, f),
    orderid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.order.ToOrderResult}
 */
proto.order.ToOrderResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.order.ToOrderResult;
  return proto.order.ToOrderResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.order.ToOrderResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.order.ToOrderResult}
 */
proto.order.ToOrderResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.HandleResult;
      reader.readMessage(value,common_pb.HandleResult.deserializeBinaryFromReader);
      msg.setHandleresult(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.order.ToOrderResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.order.ToOrderResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.order.ToOrderResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.order.ToOrderResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHandleresult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.HandleResult.serializeBinaryToWriter
    );
  }
  f = message.getOrderid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional common.HandleResult handleResult = 1;
 * @return {?proto.common.HandleResult}
 */
proto.order.ToOrderResult.prototype.getHandleresult = function() {
  return /** @type{?proto.common.HandleResult} */ (
    jspb.Message.getWrapperField(this, common_pb.HandleResult, 1));
};


/**
 * @param {?proto.common.HandleResult|undefined} value
 * @return {!proto.order.ToOrderResult} returns this
*/
proto.order.ToOrderResult.prototype.setHandleresult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.order.ToOrderResult} returns this
 */
proto.order.ToOrderResult.prototype.clearHandleresult = function() {
  return this.setHandleresult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.order.ToOrderResult.prototype.hasHandleresult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string orderId = 2;
 * @return {string}
 */
proto.order.ToOrderResult.prototype.getOrderid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.order.ToOrderResult} returns this
 */
proto.order.ToOrderResult.prototype.setOrderid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.order);
